name: Pre-submit Build

on:
  pull_request:

jobs:
  build:
    name: Build OCI image
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3

    - uses: chainguard-dev/actions/setup-registry@main
      with:
        port: 5000

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.3.*'
        terraform_wrapper: false

    - run: |
        export TF_VAR_target_repository=localhost:5000/apko
        terraform init
        terraform apply -auto-approve
